qcom

diff --git a/qcom b/qcom
--- a/qcom
+++ b/qcom
@@ -31,6 +31,7 @@ execute () {
 	fi	
 }
 
+
 #check for flags
 
 while :; do
@@ -65,6 +66,11 @@ done
 
 if [ $# == 1 ]; then
 	cd $1
+
+	if [ $? == 1 ]; then
+		echo "cd to directory failed"
+		exit 1
+	fi
 	execute
 	cd $wdir
 	exit 0
